[package]
name = "chf-rs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chf-rs-lib = { path = "../lib" }
wasm-bindgen = "0.2"
anyhow = "1.0.44"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen-test = "0.3"
