[package]
name = "chf-rs-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chf-rs-lib = { path = "../lib" }
glob = "0.3.2"
deku = "0.18.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
